<a href="https://colab.research.google.com/github/MelodyFox/Snakycode/blob/main/nmpyy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
arr= np.array([1,2,3,4,5])
l= arr.tolist()
print(l)




[1, 2, 3, 4, 5]


In [8]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
s=arr.trace()
print(arr)
print(s)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
15


In [18]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
x=int(input("enter any number"))
l=[]
for i in arr:
  if (i>x).any():
    l.append(i)
print(l)



enter any number3
[array([4, 5, 6])]


In [30]:
import numpy as np
arr1=np.array([[1,2,3],[3,4,5]])
arr2=np.array([[11,12,13],[14,15,16]])
l1=arr1.tolist()
l2=arr2.tolist()
l3=[]
for i in l1:
    for i2 in l2:
      l3.append(i+i2)
arr3=np.array(l3)
print(arr3)

[[ 1  2  3 11 12 13]
 [ 1  2  3 14 15 16]
 [ 3  4  5 11 12 13]
 [ 3  4  5 14 15 16]]


In [38]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
for a in range(1,2):
  m=np.mean(arr,axis=a)
  i=np.where(m)  
arr1= np.delete(arr,i)
print(arr1)

[4 5 6 7 8 9]
